#访问端口号
server:
  port: 8098
  #编码格式
  tomcat:
    uri-encoding: utf-8

#数据库相关配置
spring:
  ####数据源相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/admin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: QBL34YoK1Qn
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 39.105.122.45
    port: 13679
    database: 0 # 设置数据库索引为0 默认为0
    password: =HL9^cRgImw!nSj_ # 密码为空
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
    timeout: 100000 # 连接超时时间（毫秒）


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bulingbuling.admin.server
logging:
  level:
    root: INFO
    com.anran.projectmanage.mapper: DEBUG
  file:
    name: /usr/log/bulingbuling.log

feign:
  hystrix:
    enabled: true
