#访问端口号
server:
  port: 8098
  #编码格式
  tomcat:
    uri-encoding: utf-8

#数据库相关配置
spring:
  ####数据源相关配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bulingbuling?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bulingbuling.admin.server
logging:
  level:
    root: INFO
    com.anran.projectmanage.mapper: DEBUG
  file:
    name: /usr/log/bulingbuling.log

feign:
  hystrix:
    enabled: true
